# -*- coding: utf-8 -*-
"""Saitej EDA Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YV4p0C1QkDPclmUvmIs_CSDVEkps9Zk5

# **Project Name**    - Hotel Booking Analysis

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Name**: Saitej Srimal

# **Project Summary -**
This given project is all about Hotel Booking data Analysis. Which contains the real world data record of hotel bookings of a city and a resort hotel containing details like bookings, cancellations, guest details etc. It has 119390 rows and 32 columns. Main aim  of the project is to understand and visualize dataset from hotel and customer point of view i.e. reasons for booking cancellations across various parameters, best time to book hotel, peak season
and give suggestions to reduce these cancellations and increase revenue of hotels. The main objective of this project is to explore and analyze data to discover important factors that govern the bookings and give insights to the hotel management, which can perform various campaigns to boost the business and performance. 
In this project we will be dividing the data manipulation workflow in three category i.e Data collections, Data cleaning, Data manipuation, and EDA(Exploratory Data Analysis). In Data collections first step to find the different columns which is done by coding info(), describe(), columns(), and some other method which is used for data collections. We can also update some functions i.e hotel, is_cancelled, lead_time,arrival_date_year, arrival_date,month, arrival_date,week, number, arrival_date_week_number, arrival_date_day_of_months, stays_in_weekend_nights. Before Visualize any data from the data set we have to do data wrangling. For that, we will check the null values of the columnns. After checking, we will a get a column which includes more numbers of null values, and dropping that column by using 'drop' method. In this manner, we dropped the 'company' column. When we find the minimal numbers of null values with necessary values, fill these null values with necessary values as per requirement by using.fillna().  
Different charts are used for data visualization so that better insights and business objective is attained.

# **GitHub Link -**

# **Problem Statement**

Have you ever wondered when the best time of year to book a hotel room is? or the optimal length of stay in order to get the best daily rate? This hotel booking dataset can help you explore those questions! This dataset contains booking information for a city hotel and a resort hotel.

Hotel industry is a very volatile industry and the bookings depends on above factors and many more.
The main objective behind this project is to explore and analyse data to discover important factor that govern the bookings and give insights to hotel management,which can perform various campaigns to boost the business and performance.

#### **Define Your Business Objective?**

Analysizing the data on bookings of the city hotel and resort hotel to gain insights on the different factors that affect the booking.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required. 
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits. 
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule. 

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
from datetime import datetime
import seaborn as sns
import ast

from google.colab import drive
drive.mount('/content/drive')

"""### Dataset Loading"""

# Load Dataset
file_path = '/content/Hotel Bookings.csv'
df=pd.read_csv(file_path)
hotel_booking_df = pd.read_csv(file_path)

"""### Dataset First View"""

# Dataset First Look
hotel_booking_df

"""# Value Counts"""

hotel_booking_df.value_counts()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(hotel_booking_df.index)
print('\n')
print(hotel_booking_df.columns)

"""### Dataset Information"""

# Dataset Info
hotel_booking_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count, to remove these values, we use function drop.duplicate to delete duplicate rows.
hotel_booking_df.drop_duplicates(inplace = True)

# total rows = 119390, Duplicate Rows = 31994
uni_num_of_rows = hotel_booking_df.shape[0]

uni_num_of_rows # now unique rows = 87396

# Viewing unique data.
hotel_booking_df.reset_index()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
null_value = hotel_booking_df.isnull() == True
hotel_booking_df.fillna(np.nan, inplace = True)

# Replacing all the null value as NaN.
hotel_booking_df

# Visualizing the missing values
miss_values =hotel_booking_df.isnull().sum().sort_values(ascending=False)

# Analysing the count of null value in individual columns.
miss_values

"""### What did you know about your dataset?

This data set contains a single file which compares various booking information between two hotels i.e = a city hotel and resort hotel. Which also includes information such as when the booking was made, days of stay, the number of adults, children, and/or infants(babies), and the number of available parking spaces, among other things. The data set contains a 119390 rows and 32 columns. Dataset contains duplicated items i.e 31944 which was removed later. In this dataset we will find data types of each and every columns i.e (int, float, string) and observe some columns data type is not accurate and removed later. We fill find unique values of every columns which means the actual values of every column.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df_column = hotel_booking_df.columns
df_column

# Dataset Describe
hotel_booking_df.describe()

"""### Variables Description

# **The columns and the data it represents are listed below:**
**1.hotel**: Name of the hotel(Resort hotel or city hotel).                            
**2.is_cancelled**: If the booking was cancelled(1) or not(0).                         
**3.lead_time**: Number of days before the actual arrival of the guests.          
**4.arrival_date_year:** Date and year for arrival.                                                                        
**5.arrival_date_month**: Date and month for arrival.                                                                        
**6.arrival_date_week_number**: Arrival date week.                                
**7.arrival_date_day_of_month**: Date with day and month of arrival.                  
**8.stays_in_weekend_nights**: Number of weekend nights spent at the specific hotel by the guests.                                                        
**9.stays_in week_nights**: Number of week days (Monday to Friday) spent at the specific hotel by the guests.                                                    
**10.adults**: Number of adults among the guests.                                
**11.children**: Number of children among the guests.                            
**12.babies**: Number of babies among the guests.                                 
**13.meal**: Type of meal boked.                                                  
**14.country**: From which country do guests belong.                              
**15.market_segment**: Designation of market segment.                            
**16.distribution_channel**: Name of the booking distribution channel.               
**17.is_repeated_guests**: If the booking was from a repeated guests(1) or not(0).                                                                           
**18.previous_cancellations**: Number of previous bookings that were cancelled by the customer prior to the current booking.                                     
19.**previous_bookings_not_cancelled**: Number of previous bookings that were not  cancelled by the customer prior to the current booking.                      
**20.reserved_room_type**: The type of room reserved by the guests.                  
**21.assigned_room_type**: The type of room assigned by the guests.               
**22.booking_changes**: The number of changes made on the booking.                 
**23.deposit_type**: Type of deposit made by the guests.                           
**24.agent**: ID of travel agent who made booking.                                      
**25.company**:ID of travel company who made booking.                                  
**26.days_in_waiting_list**: Number of days of showing the rooms in waiting list.                                                                           
**27.customer_type**: Type of customer, assuming one of four categories.          
**28.adr**: Average daily rate, as defined by dividing the sum of all lodging transactions by the total number of staying nights.                              
**29.required_car_parking_space**: Number of car parking space required for the guests.           
**30.total_of_special_requests**: Number of special requests made by the customer.                                                                
**31.reservation_status**: Reservation status(Cancelled, check-out,check-in)         
**32.reservation_status_date**: Date at which the last reservation status was updated.

### Check Unique Values for each variable.
"""

# Analysing Unique Values for each variable.
 # Describing unique value in all individual column.
print(hotel_booking_df.apply(lambda col: col.unique()))

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

#To fill the NaN value in the column, let's analyse which columns has null value, that have already stored the same.
miss_values[:4]

#Analysing, what is the percentage of null value in each column, checking from company.

percentage_company_null = miss_values[0] / uni_num_of_rows*100
percentage_company_null

# It is better to drop the column 'company' altogether since the number of missing values is extremely high compared to the number of rows.

hotel_booking_df.drop(['company'], axis=1, inplace=True)

#Analysing for agent.

percentage_agent_null = miss_values[1] / uni_num_of_rows*100
percentage_agent_null

#As we had seen there is minimul null values in agent, let's fill these value by taking mode of the all values.
hotel_booking_df['agent'].fillna(value = 0, inplace = True)
hotel_booking_df['agent'].isnull().sum # Re-checking that column has no null value

#Analysing the percentage of country null values.
percentage_country_null = miss_values[2] / uni_num_of_rows * 100
percentage_country_null

# We have less null values in country column, so we will replace null from 'other' as country name.
hotel_booking_df['country'].fillna(value = 'others', inplace = True)
hotel_booking_df['country'].isnull().sum()

#Analysing the percentage of children null values.
percentage_children_null = miss_values[3] / uni_num_of_rows * 100
percentage_children_null

# we have less null values in country column, so we will replace null from 0 as country name.
hotel_booking_df['children'].fillna(value = 0, inplace = True)
hotel_booking_df['children'].isnull().sum()

#Analysing whether database having any other null values.
hotel_booking_df.isnull().sum()

"""# **Change in datatype for required columns**"""

#viewing the info of the data to analyse(check) datatype.
hotel_booking_df.info()

# We have seen that childern & agent column as datatype as float whereas it contains only int value, lets change datatype as 'int64'
hotel_booking_df[['children', 'agent']] = hotel_booking_df[['children', 'agent']].astype('int64')

"""# **Addition of new column as per requirement**"""

#sum(total) of stay in nights.
# We have created a col for total stays in nights by adding week night & weekend nights stay col.
hotel_booking_df['total_stay_in_nights'] = hotel_booking_df ['stays_in_week_nights'] + hotel_booking_df ['stays_in_weekend_nights']
hotel_booking_df['total_stay_in_nights']

# Created a col for revenue using total stay * adr
hotel_booking_df['revenue'] = hotel_booking_df['total_stay_in_nights'] *hotel_booking_df['adr']
hotel_booking_df['revenue']

# I will be adding a column with total number of guests comimg for each booking for information purpose.
hotel_booking_df['total_guest'] = hotel_booking_df['adults'] + hotel_booking_df['children'] + hotel_booking_df['babies']
hotel_booking_df['total_guest'].sum()

# for understanding, from col 'is_canceled': we will replace the value from (0,1) to not_canceled, is canceled.

hotel_booking_df['is_canceled'] = hotel_booking_df['is_canceled'].replace([0,1], ['not canceled', 'is canceled'])
hotel_booking_df['is_canceled']

#Same for 'is_repeated_guest' col
hotel_booking_df['is_repeated_guest'] = hotel_booking_df['is_repeated_guest'].replace([0,1], ['not repeated', 'repeated'])
hotel_booking_df['is_repeated_guest']

#Analysing the overall revenue hotel wise
hotel_wise_total_revenue = hotel_booking_df.groupby('hotel')['revenue'].sum()
hotel_wise_total_revenue

hotel_booking_df[['hotel', "revenue"]]



"""### What all manipulations have you done and insights you found?

# **We have done few manipulations in the Data.**

# We have seen that there are few columns required in Data to analysis purpose which can be evaluated from the given columns.

a) **Total Guests**: This columns will help us to evaluate the volumes of total guest and revenue as well. We get this value by adding total no. of Adults, Children & babies.

b) **Revenue**: We find revenue by multiplying adr & total guest. This column will use to analyse the profit and growth of each hotel.

**----Delete of columns----**

a)**company**: As we have seen that this columns has almost Null data. so we had to delete this column as this will not make any impact in the analysis.

**----Replace of Values in columns----**

a)**is_canceled, is_not_canceled & is_repeated_guest**: We have seen, that these columns contains only 0,1 as values which represent the status of booking cancellation. We replace these values (0,1) from 'Canceled' & 'Not canceled. In the same way for column 'is_repeated_guest', we replace 0,1 from 'Repeated' & 'Not repeated'. Now this values will help to make better understanding while visulization.

**----Changes in data type of values in columns----**

a)**Agent & Children**: We checked that these columns contains float values, which is not making any sense in data as this values represent the count of guest & ID of agent. So we have changed the data type of these columns from 'float' to 'Integer'.

**----Removed is_null values & duplicate entries----**

a)Before visualize any data from the data set we have to do data wrangling. For that, we have checked the null value in all the columns. After checking, when we will get a column which has more number of null values, drop that column by using the 'drop' method. In this way, we are dropping the 'company' column. When we are find minimal number of null values, filling these null values with necessary values as per requirement by using .fillna().

b) In the same, we have checked if there is any duplicacy in data and we found that there are few rows have duplicate data. So we have removed those row from data set by using .drop_duplicates() method.

**In this way, we have removed unneccesary data & made our data clean and ready to analyse.**

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1

# **Q.1) Which type of Hotel as highest number of bookings?**
"""

# Let's create a function which will give us bar chart of data with a column.
def get_count_from_column_bar(df, column_label):
  df_grpd = df[column_label].value_counts()
  df_grpd = pd.DataFrame({'index':df_grpd.index, 'count':df_grpd.values})
  return df_grpd


def plot_bar_chart_from_column(df, column_label, t1):
  df_grpd = get_count_from_column(df, column_label)
  fig, ax = plt.subplots(figsize=(14, 6))
  c= ['g','r','b','c','y']
  ax.bar(df_grpd['index'], df_grpd['count'], width = 0.4, align = 'edge', edgecolor = 'black', linewidth = 4, color = c, linestyle = ':', alpha = 0.5)
  plt.title(t1, bbox={'facecolor':'0.8', 'pad':3})
  plt.legend()
  plt.ylabel('Count')
  plt.xticks(rotation = 15) # use to format the lable of x-axis
  plt.xlabel(column_label)
  plt.show()

# Chart - 1 visualization code
def get_count_from_column(df, column_label):
  df_grpd = df[column_label].value_counts()
  df_grpd = pd.DataFrame({'index':df_grpd.index, 'count':df_grpd.values})
  return df_grpd

# plot a pie chart from grouped data
def plot_pie_chart_from_column(df, column_label, t1, exp):
  df_grpd = get_count_from_column(df, column_label)
  fig, ax = plt.subplots(figsize=(14,9))
  ax.pie(df_grpd.loc[:, 'count'], labels=df_grpd.loc[:, 'index'], autopct='%1.2f%%',startangle=90,shadow=True, labeldistance = 1, explode = exp)
  plt.title(t1, bbox={'facecolor':'0.8', 'pad':3})
  ax.axis('equal')
  plt.legend()
  plt.show()

exp1 = [0.05,0.05]
plot_pie_chart_from_column(hotel_booking_df, 'hotel', 'Booking percentage of Hotel by Name', exp1)

"""##### 1. Why did you pick the specific chart?

**To Represent the data in which hotel there is the highest number of booking had been done.**

##### 2. What is/are the insight(s) found from the chart?

**Here, we found that the number of booking is Higher in City Hotel which is 61.12% than Resort Hotel which is just 38.87%. Hence, we can say that City hotel has more consumption**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, obiviously for both Hotels, and this data makes perfect positive business impact : -**

**City Hotel** :- **Provides more services to attract more guests which will help in increasing more revenue.**

**Resort Hotel**:- **Find's the solution to attract guests and also finds which hotel did attracts the most for guests.**

#### Chart - 2

# **Q.2) Which Hotel has Highest Volume of Cancellations?**
"""

# Chart - 2 visualization code
exp4 = [0,0.2]
plot_pie_chart_from_column(hotel_booking_df, 'is_canceled', 'Cancellation volume of Hotel', exp4)

"""##### 1. Why did you pick the specific chart?

**To Represent the cancellation rate of the hotels booking**.

##### 2. What is/are the insight(s) found from the chart?

**We found that overall more than 25% of booking got cancelled.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Here, we can see, that the more than 27% of booking are getting cancelled.**

**Solution: We can check the reason for cancellation of a booking and should need to get this sort on business level**.

#### Chart - 3

# **Q.3) Which Channel Has The Highest Volume of Bookings?**
"""

# Chart - 3 visualization code
plot_bar_chart_from_column(hotel_booking_df, 'distribution_channel', 'Distibution Channel Volume')

"""##### 1. Why did you pick the specific chart?

**To represent from which channel the maximum number of booking had done and to represent the numbers in descending order we chose bar graph.**

##### 2. What is/are the insight(s) found from the chart?

**As we see Tour of Agent and Tour of operator is highest, recommending to continue booking through Tour of Agent and Tour of operator.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**This shows a positive business impact.**

**The higher the number of Tour of agent and Tour of operator it will help to increase the revenue generation of Hotel.**

#### Chart - 4

# **Q.4) Which Month Has The Highest Number Of Bookings?**
"""

# Chart - 4 visualization code
exp2 = [0.2, 0,0,0,0,0,0,0,0,0,0,0.1]
plot_pie_chart_from_column(hotel_booking_df, 'arrival_date_month', 'Month-wise booking', exp2)

"""##### 1. Why did you pick the specific chart?

**To represents the percentage share of booking in a sequence of month wise booking**.

##### 2. What is/are the insight(s) found from the chart?

**The above chart shows the percentage of month May, July and Aug these are the highest booking months due to holiday season. Recommending the aggressive of  advertisement can lure more and more customers**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**obiviously, by the increased volume of visitors it helps the hotel, which manage revenue in the down time, it will also help in employer's satisfaction and retention**.

#### Chart - 5

# **Q.5) What Is the Percentage Of Non Repeated Guests?**
"""

# Chart - 5 visualization code
exp3 = [0,0.3]
plot_pie_chart_from_column(hotel_booking_df, 'is_repeated_guest', 'Guest repeating status', exp3)

"""##### 1. Why did you pick the specific chart?

**To represent the chart which shows percentage share of repeated & non-repeated guests.**

##### 2. What is/are the insight(s) found from the chart?

**We can see that the number of repeated guests are very less as compared to overall guests**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We can give the alluring offers to the non-repetitive customers during Off seasons for enhancing revenue**.

#### Chart - 6

# **Q.6) which Type Of Room is Assigned The Most?**
"""

# Chart - 6 visualization code
plot_bar_chart_from_column(hotel_booking_df, 'assigned_room_type', 'Assigment of room by type')

"""##### 1. Why did you pick the specific chart?

**To represents the volume, about the room alotted**.

##### 2. What is/are the insight(s) found from the chart?

**This graph shows the room type 'A' is most prefered by guests**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, it shows a Positive impact and the reason is 'A','D','E' is more prefered by guest due to better services offered in room type.**

#### Chart - 7

# **Q.7) Which Channel Has The Highest Rate of Bookings?**
"""

guest_month_wise = pd.DataFrame(hotel_booking_df[['arrival_date_month', 'total_guest']])
guest_month_wise_df = guest_month_wise.groupby(['arrival_date_month'])['total_guest'].sum()
guest_month_wise_df.sort_values(ascending = False, inplace = True)

hotel_booking_df['total_guest']

# Chart - 7 visualization code
market_segment_df = pd.DataFrame(hotel_booking_df['market_segment'])
market_segment_df_data = market_segment_df.groupby('market_segment')['market_segment'].count()
market_segment_df_data.sort_values(ascending = False, inplace = True)
plt.figure(figsize=(15,6))
y = np.array([4,5,6])
market_segment_df_data.plot(kind = 'bar', color=['g', 'r', 'c', 'b', 'y', 'black', 'brown'], fontsize = 20,legend='True')

"""##### 1. Why did you pick the specific chart?

**To represent the market segment by which hotel has been booked**.

##### 2. What is/are the insight(s) found from the chart?

**The Online TA(Tour of agent) has been used most frequently to book the hotel by the guest**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, it is creating a positive business impact as guests are using the Online TA market segment as most prefered for booking the hotels**.

#### Chart - 8

# **Q.8) Which Are The Top 10 Countries Visits The Most?**
"""

# Chart - 8 visualization code
guest_country_wise = pd.DataFrame(hotel_booking_df[['country', 'total_guest']])
guest_country_wise_df = guest_country_wise.groupby(['country'])['total_guest'].sum()
guest_country_wise_df.sort_values(ascending = False, inplace = True)
top_10_country_by_guest = guest_country_wise_df.head(10)

plt.figure(figsize=(12,6))
sns.barplot(top_10_country_by_guest.index, top_10_country_by_guest).set(title='Top 10 Countries by Guest')
print("\n\nPRT = Portugal\nGBR = Great Britain & Northern Ireland\nFRA = France\nESP = Spain\nDEU = Germany\nITA = Italy\nIRL = Ireland\nBRA = Brazil\nBEL = Belgium\nNLD = Netherland")

"""##### 1. Why did you pick the specific chart?

**To represent from which country the most of guests are visiting and this graph shows for top 10 countries**.

##### 2. What is/are the insight(s) found from the chart?

**As we can see, that the maximum guests are visiting from Portugal**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We can do more advertising and can provide a attractive offers to Portugal guests for enhance the customer volume**.

#### Chart - 9

# **Q.9) Which Month Has The Highest Ratre Of Bookings?**
"""

# Chart - 9 visualization code
order = ['January', 'February', 'March', 'April', 'May', 'June', 
         'July', 'August', 'September', 'October', 'November', 'December']
ordered_hotel_df = hotel_booking_df[hotel_booking_df['is_canceled'] == 'not canceled']['arrival_date_month'].value_counts().reindex(order)
plt.subplots(figsize=(10, 6))
ticks = np.arange(0, 20, 150)
labels = ["{}".format(i//1) for i in ticks]
plt.yticks(ticks, labels)

plt.xticks(rotation=60)

for xy in zip(ordered_hotel_df.index, ordered_hotel_df.values):
    plt.annotate(s = "{}".format(xy[1]//1), xy = xy,  textcoords='data')

plt.plot(ordered_hotel_df.index, ordered_hotel_df.values,linewidth = 4, color = 'r',linestyle='dotted',marker='+',markersize=20,alpha=1)

plt.xlabel("Months", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Brown'})
plt.ylabel("Counts", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Brown'} )
plt.title("Month-wise Booking", fontdict={'fontsize': 20, 'fontweight' : 5, 'color' : 'Green'} )

"""##### 1. Why did you pick the specific chart?

**To represents the highest rate of bookings**.

##### 2. What is/are the insight(s) found from the chart?

**From june to august the number of bookings are at peak level**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We can do more advertising for the City hotel to get more customer, which results in the higher profits**.

#### Chart - 10

# Q.10) **Why The ADR Is Getting Increased?**
"""

# Chart - 10 visualization code
plt.figure(figsize = (12,6))
sns.scatterplot(y = 'total_stay_in_nights', x = 'adr', data = hotel_booking_df[hotel_booking_df['adr'] < 1000])
plt.show()

"""##### 1. Why did you pick the specific chart?

**The following graph represents the comparision and affect of total stay days vs ADR**.

##### 2. What is/are the insight(s) found from the chart?

**If guest's vaccating days is getting decreased, ADR is getting increased**.

#### Chart - 11

# **Q,11) Which Type Of Meal Is Most Preferanced By The Guests?**
"""

# Chart - 11 visualization code
plt.figure(figsize = (12,10), dpi = 100)
hotel_wise_meal = hotel_booking_df.groupby(['hotel', 'meal'])['meal'].count().unstack()
hotel_wise_meal.plot(kind ='bar', figsize = (12,8))
hotel_wise_meal

"""##### 1. Why did you pick the specific chart?

**To represent the meal preferance of the guests hotel-wise**.

##### 2. What is/are the insight(s) found from the chart?

**As we can see that, BB (Bed & breakfast) meal is most prefered by guests in both the hotels. So Hotel can give more delicious dishes in the meal to get customer attaracted with the new customer**.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, it will impact on the rating of the hotel.

#### Chart - 12

# **Q.12) Which Hotel Has Highest Revenue?**
"""

# Chart - 12 visualization code
plt.figure(figsize = (8,5))
hotel_wise_revenue = hotel_booking_df.groupby('hotel')['revenue'].sum()
hotel_wise_revenue
ax = hotel_wise_revenue.plot(kind = 'bar', color = ('b', 'y'))
plt.xlabel("Hotel", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Brown'})
plt.ylabel("Total Revenue", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Brown'} )
plt.title("Total Revenue", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Green'} )

"""##### 1. Why did you pick the specific chart?

**To represent the highest rate of revenue.**

##### 2. What is/are the insight(s) found from the chart?

**City hotel has highest revenue than Resort Hotel.**

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**Proper way of advertising can make huge difference.**

#### Chart - 13
"""

# Chart - 13 visualization code
average_adr = hotel_booking_df.groupby('hotel')['adr'].mean()
average_adr
plt.subplots(figsize=(8, 5))
average_adr.plot(kind = 'barh', color = ('g', 'r'))
plt.xlabel("Average ADR", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Brown'})
plt.ylabel("Hotel Name", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Brown'} )
plt.title("Average ADR of Hotel", fontdict={'fontsize': 12, 'fontweight' : 5, 'color' : 'Green'} )

"""##### 1. Why did you pick the specific chart?

**To represent the highest ADR**.

##### 2. What is/are the insight(s) found from the chart?

**City hotel has the Highest ADR Then, Resort hote**l.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

**We can do more advertising for the City hotel to get more customer, which results in the higher profit**s.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
corr_df = hotel_booking_df[['lead_time','previous_cancellations', 'previous_bookings_not_canceled', 'total_guest',
                    'booking_changes', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests']].corr()
f, ax = plt.subplots(figsize=(12, 12))
sns.heatmap(corr_df, annot = True, fmt='.2f', annot_kws={'size': 10},  vmax=1, square=True, cmap="YlGnBu")

"""##### 1. Why did you pick the specific chart?

**To represents the relation between different numerical values of every data**.

##### 2. What is/are the insight(s) found from the chart?

**ADR is slightly correlated with total_people, which makes sense as more number of people means more revenue, therefore more ADR.**

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ? 
Explain Briefly.

# **The Business objective are as follows**:
1.For hotel business to the flourish few things which we need to consider is high revenue generation, customers satisfaction and employeee retention.                                                     

2.We are able to achieve the same thing by showing the client that which are the months and which are high in revenue from generated by pie chart distribution.                                                  

3.Increasing in the revenue which has achieved by the bar chart distribution and which type of rooms are the most reserved and at which months the visitors are likely to visit.                                 

4.So for these are the clients and can be well prepared in advance so that the minimum grievances would be faced by clients in long run and would help in further enhancement of their hospitality.                        

5.Outliers like the higher the visitor then the adr had been reduced to drastically as shown in the scattered plot, so that in off season the client can engage with offices for bulk booking and this will also help in extra revenue generation.                                             

6.We are able to show the trends of arrivals for visitors at their client locations through which client had engaged with visiters well and for advance there entertainment and leisure activities.

7.We are also able to co relate the values showing the maximum and minimum percentage between them so that the percentage lying those numbers can be enhanced by various medium.

# **Conclusion**

1.The guests are more likely to be preffered city hotels and it also creates more earnings and good gain profit.                                                                 

2.Approximately 60% of bookings are considered as for the city hotel, and remaining 40% is for the resort hotel.

3.Oftenly,the booking accuracy is higher in the month of july and august in contrast to(compared) remaining of the months.

4.Mainly the guests prefer to stay no longer than 3 to 5 days and if for longer days they prefer resort hotel.

5.The most of the guests are from visitig Portugal and Europian countries.

6.Type A room is most preferred room among the guests.                                                                 

7.The guests mainly prefer TA/TO for making bookings.

8.Approximarely, the 25 to 35% bookings done by TA/TO are cancelled.     

9.The new guests used to cancell the most than the repeated guests.                                                                 

10.The most common guests for the hotels are couples, by planning and service hotels can increase their profit.                                                                 

11.For customers, generally the longer stays (more than 15 days) can result in better deals in terms of low adr.
If the customers(guests) stays longer than 11-15 days they can result in a better deals, like low adr.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""